### ISSUE TITLE
User account provisioning

### ISSUE THREAD

**Issue by luxaritas** [muctadir/lama#16]
I imagine in many installations, admins would want to only allow specific individuals to create accounts. It should probably be possible to turn off public account creation in favor of just sending email invites to provision new accounts.

Submitted while reviewing https://github.com/openjournals/joss-reviews/issues/5135

**Comment by JarlJansen123** [comment]
Interesting suggestion. We are looking at implementing something like this in the next few days.

**Comment by JarlJansen123** [comment]
We have implemented something very similar to what you have described here. There is now an environment variable "AUTO_APPROVAL" if this is set to false, then when a user creates a new account it will be pending approval by a super-admin. In other words, there is now control over who can and who can't create an account. 

We opted for this implementation over your suggestion using email since we think it is important that this functionality is also usable without access to an email server. 

We have provided a short description on the details of how this all works in the section "environment variables" in the readme.
